server: 
  port: 2000 
spring: 
  application: 
    name: welisit-crowd-mysql 
  datasource: 
    name: mydb 
    type: com.alibaba.druid.pool.DruidDataSource 
    url: jdbc:mysql:///project_crowd?serverTimezone=UTC 
    username: root 
    password: 123 
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka: 
  client: 
    service-url: 
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml

logging: 
  level: 
    com.welisit.crowd.mapper: debug 
    com.welisit.crowd.test: debug